Repository softeerbootcamp4th/Team8-PineApple-BE, pull requests merged in 2024-08, with the labels that each got.

#24 Feat/#22,23/예외처리 및 검증처리 기본 뼈대 구현
  build.gradle
  src/main/java/softeer/team_pineapple_be/domain/comment/controller/CommentController.java
  src/main/java/softeer/team_pineapple_be/domain/member/controller/LoginController.java
  src/main/java/softeer/team_pineapple_be/domain/member/request/LoginAuthCodeRequest.java
  src/main/java/softeer/team_pineapple_be/domain/member/request/LoginPhoneNumberRequest.java
  src/main/java/softeer/team_pineapple_be/global/auth/exception/AuthErrorCode.java
  src/main/java/softeer/team_pineapple_be/global/auth/service/AuthMemberService.java
  src/main/java/softeer/team_pineapple_be/global/common/response/ErrorResponse.java
  src/main/java/softeer/team_pineapple_be/global/config/CorsMvcConfig.java
  src/main/java/softeer/team_pineapple_be/global/config/MessageConfig.java
  src/main/java/softeer/team_pineapple_be/global/exception/CommonErrorCode.java
  src/main/java/softeer/team_pineapple_be/global/exception/ErrorCode.java
  src/main/java/softeer/team_pineapple_be/global/exception/RestApiException.java
  src/main/java/softeer/team_pineapple_be/global/exception/handler/RestApiExceptionHandler.java
  src/main/resources/application.yml
  src/main/resources/messages.properties
Labels: 설정 추가, 버그 픽스, 기능 추가, 예외처리

#39 Feat/#31/인증 방식을 JWT 인증으로 변경
  build.gradle
  src/main/java/softeer/team_pineapple_be/domain/comment/controller/CommentController.java
  src/main/java/softeer/team_pineapple_be/domain/draw/controller/DrawController.java
  src/main/java/softeer/team_pineapple_be/domain/member/controller/LoginController.java
  src/main/java/softeer/team_pineapple_be/domain/member/domain/Member.java
  src/main/java/softeer/team_pineapple_be/domain/member/response/MemberLoginInfoResponse.java
  src/main/java/softeer/team_pineapple_be/domain/member/service/MemberAuthorizationService.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/controller/QuizController.java
  src/main/java/softeer/team_pineapple_be/domain/worldcup/controller/WorldCupController.java
  src/main/java/softeer/team_pineapple_be/global/auth/annotation/Auth.java
  src/main/java/softeer/team_pineapple_be/global/auth/context/AuthContext.java
  src/main/java/softeer/team_pineapple_be/global/auth/context/AuthContextHolder.java
  src/main/java/softeer/team_pineapple_be/global/auth/exception/AuthErrorCode.java
  src/main/java/softeer/team_pineapple_be/global/auth/filter/ThreadLocalCleanerFilter.java
  src/main/java/softeer/team_pineapple_be/global/auth/interceptor/JwtInterceptor.java
  src/main/java/softeer/team_pineapple_be/global/auth/service/AuthMemberService.java
  src/main/java/softeer/team_pineapple_be/global/auth/utils/JwtUtils.java
  src/main/java/softeer/team_pineapple_be/global/config/FilterConfig.java
  src/main/java/softeer/team_pineapple_be/global/config/InterceptorConfig.java
Labels: 설정 추가, 기능 개선, 기능 추가, 예외처리

#37 Feat/#36/QuizController 테스트 코드 작성
  src/test/java/softeer/team_pineapple_be/domain/quiz/controller/QuizControllerTest.java
  src/test/java/softeer/team_pineapple_be/domain/quiz/service/QuizServiceTest.java
Labels: 기능 추가

#43 [FIX] PreFlight 요청 막히는 버그 안잡혀서 다시 수정
  src/main/java/softeer/team_pineapple_be/global/auth/interceptor/JwtInterceptor.java
Labels: 버그 픽스

#40 Feat/#38/WorldCup 테스트 코드 작성
  src/test/java/softeer/team_pineapple_be/domain/worldcup/controller/WorldCupControllerTest.java
  src/test/java/softeer/team_pineapple_be/domain/worldcup/service/WorldCupServiceTest.java
Labels: 기능 추가

#47 Fix/#33,46/기대평 전화번호 마스킹 기능과 툴박스 얻는 기능 추가
  src/main/java/softeer/team_pineapple_be/domain/comment/response/CommentResponse.java
  src/main/java/softeer/team_pineapple_be/domain/comment/service/CommentService.java
  src/main/java/softeer/team_pineapple_be/domain/comment/utils/PhoneNumberMasker.java
Labels: 기능 개선, 버그 픽스, 기능 추가

#53 [FEAT] 레디스를 이용하여 자신이 누른 좋아요 정보를 기대평 응답에 추가
  build.gradle
  src/main/java/softeer/team_pineapple_be/domain/comment/domain/Comment.java
  src/main/java/softeer/team_pineapple_be/domain/comment/response/CommentPageResponse.java
  src/main/java/softeer/team_pineapple_be/domain/comment/response/CommentResponse.java
  src/main/java/softeer/team_pineapple_be/domain/comment/service/CommentService.java
  src/main/java/softeer/team_pineapple_be/domain/comment/service/LikeRedisService.java
  src/main/java/softeer/team_pineapple_be/global/auth/interceptor/JwtInterceptor.java
  src/main/java/softeer/team_pineapple_be/global/auth/service/AuthMemberService.java
  src/main/java/softeer/team_pineapple_be/global/config/RedisConfig.java
Labels: 설정 추가, 기능 개선, 기능 추가

#56 Feat/#55/월드컵 관련 기능 추가 (월드컵 결과 통계)
  src/main/java/softeer/team_pineapple_be/domain/quiz/response/QuizContentResponse.java
  src/main/java/softeer/team_pineapple_be/domain/worldcup/controller/WorldCupController.java
  src/main/java/softeer/team_pineapple_be/domain/worldcup/request/WorldCupResultRequest.java
  src/main/java/softeer/team_pineapple_be/domain/worldcup/response/WorldCupResultResponse.java
  src/main/java/softeer/team_pineapple_be/domain/worldcup/service/WorldCupRedisService.java
  src/main/java/softeer/team_pineapple_be/domain/worldcup/service/WorldCupService.java
  src/main/java/softeer/team_pineapple_be/global/auth/interceptor/JwtInterceptor.java
  src/main/resources/messages.properties
Labels: api 추가, 기능 추가

#62 Feat/#61/Comment schedule 기능 추가
  src/main/java/softeer/team_pineapple_be/TeamPineappleBeApplication.java
  src/main/java/softeer/team_pineapple_be/domain/comment/repository/CommentRepository.java
  src/main/java/softeer/team_pineapple_be/domain/comment/service/CommentService.java
  src/main/java/softeer/team_pineapple_be/domain/member/domain/Member.java
Labels: 기능 추가

#64 Feat/#57,63/선착순 시스템 구현, 선착순 퀴즈 상품 받기 기능 구현
  src/main/java/softeer/team_pineapple_be/domain/comment/request/CommentRequest.java
  src/main/java/softeer/team_pineapple_be/domain/fcfs/domain/FcfsInfoEntity.java
  src/main/java/softeer/team_pineapple_be/domain/fcfs/dto/FcfsInfo.java
  src/main/java/softeer/team_pineapple_be/domain/fcfs/exception/FcfsErrorCode.java
  src/main/java/softeer/team_pineapple_be/domain/fcfs/repository/FcfsInfoRepository.java
  src/main/java/softeer/team_pineapple_be/domain/fcfs/service/FcfsService.java
  src/main/java/softeer/team_pineapple_be/domain/member/controller/LoginController.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/controller/QuizController.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/domain/QuizReward.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/exception/QuizErrorCode.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/repository/QuizRewardRepository.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/request/QuizRewardRequest.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/response/QuizSuccessInfoResponse.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizService.java
  src/main/java/softeer/team_pineapple_be/domain/worldcup/controller/WorldCupController.java
  src/main/java/softeer/team_pineapple_be/global/config/LuaScriptConfig.java
  src/main/java/softeer/team_pineapple_be/global/message/MessageService.java
  src/main/resources/messages.properties
  src/main/resources/redis-script/fcfs-script.lua
Labels: 설정 추가, api 추가, 기능 개선, 기능 추가

#66 Fix/#60,65/월드컵 통계 기능 버그 수정
  src/main/java/softeer/team_pineapple_be/domain/worldcup/service/WorldCupRedisService.java
Labels: 기능 개선, 버그 픽스

#69 Feat/#54/멤버 정보 보내줄 때 당일 퀴즈 참여여부 추가
  src/main/java/softeer/team_pineapple_be/domain/member/controller/MemberController.java
  src/main/java/softeer/team_pineapple_be/domain/member/response/MemberInfoResponse.java
  src/main/java/softeer/team_pineapple_be/domain/member/response/MemberLoginInfoResponse.java
  src/main/java/softeer/team_pineapple_be/domain/member/service/MemberAuthorizationService.java
  src/main/java/softeer/team_pineapple_be/domain/member/service/MemberService.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/batch/QuizDailyBatch.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizRedisService.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizService.java
Labels: api 추가, 기능 추가

#73 Fix/#70/선착순 정보 매일 초기화하기
  src/main/java/softeer/team_pineapple_be/domain/fcfs/batch/FcfsDailyBatch.java
  src/main/java/softeer/team_pineapple_be/domain/fcfs/service/FcfsService.java
Labels: 기능 개선, 버그 픽스

#75 [FEAT] 경품 추첨 응답에 기대평 작성 여부 추가
  src/main/java/softeer/team_pineapple_be/domain/draw/response/DrawLoseResponse.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawService.java
Labels: 기능 개선, 기능 추가

#77 Feat/#72,#74/선착순 경품 관련 기능 추가
  src/main/java/softeer/team_pineapple_be/domain/quiz/controller/QuizController.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/exception/QuizErrorCode.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/response/QuizRewardCheckResponse.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizRedisService.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizService.java
Labels: api 추가, 기능 개선, 기능 추가

#76 test/#59/기대평 테스트 코드 추가 및 기존 테스트 코드 수정
  src/main/java/softeer/team_pineapple_be/domain/comment/domain/Comment.java
  src/main/java/softeer/team_pineapple_be/domain/comment/repository/CommentRepository.java
  src/main/java/softeer/team_pineapple_be/domain/comment/service/CommentService.java
  src/test/java/softeer/team_pineapple_be/domain/comment/service/CommentServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/comment/service/LikeRedisServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/member/service/MemberAuthorizationServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/quiz/controller/QuizControllerTest.java
  src/test/java/softeer/team_pineapple_be/domain/quiz/service/QuizServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/worldcup/service/WorldCupRedisServiceTest.java
  src/test/java/softeer/team_pineapple_be/global/auth/utils/JwtUtilsTest.java
Labels: 기능 개선

#80 Fix/#79/머지 시에 생긴 에러 처리
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawService.java
  src/test/java/softeer/team_pineapple_be/domain/draw/contorller/DrawControllerTest.java
  src/test/java/softeer/team_pineapple_be/domain/draw/service/DrawServiceTest.java
Labels: 버그 픽스

#84 Feat/83/퀴즈 관련 어드민 기능 추가, S3,Querydsl 설정 추가
  build.gradle
  src/main/java/softeer/team_pineapple_be/domain/admin/controller/AdminController.java
  src/main/java/softeer/team_pineapple_be/domain/admin/domain/EventDayInfo.java
  src/main/java/softeer/team_pineapple_be/domain/admin/exception/AdminErrorCode.java
  src/main/java/softeer/team_pineapple_be/domain/admin/repisotory/EventDayInfoRepository.java
  src/main/java/softeer/team_pineapple_be/domain/admin/service/EventDayInfoService.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/dao/QuizDao.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/domain/QuizContent.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/request/QuizModifyRequest.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/response/QuizAnswerResponse.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizService.java
  src/main/java/softeer/team_pineapple_be/global/cloud/service/S3UploadService.java
  src/main/java/softeer/team_pineapple_be/global/config/CorsMvcConfig.java
  src/main/java/softeer/team_pineapple_be/global/config/QuerydslConfig.java
  src/main/java/softeer/team_pineapple_be/global/config/S3Config.java
Labels: 설정 추가, api 추가, 기능 개선, 버그 픽스, 기능 추가

#86 Feat/#85/퀴즈 어드민 기능 완성, Swagger 추가
  src/main/java/softeer/team_pineapple_be/domain/admin/controller/AdminController.java
  src/main/java/softeer/team_pineapple_be/domain/draw/controller/DrawController.java
  src/main/java/softeer/team_pineapple_be/domain/member/controller/MemberController.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/dao/QuizDao.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/domain/QuizInfo.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/request/QuizInfoModifyRequest.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/request/QuizModifyRequest.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizService.java
  src/main/resources/messages.properties
Labels: 설정 추가, api 추가, 기능 추가

#89 Feat/#88. #90/Admin이 zip파일을 이용하여 S3에 상품에 대한 정보를 추가할 수 있는 서비스 구현
  src/main/java/softeer/team_pineapple_be/domain/admin/controller/AdminController.java
  src/main/java/softeer/team_pineapple_be/domain/admin/exception/AdminErrorCode.java
  src/main/java/softeer/team_pineapple_be/domain/draw/domain/DrawPrize.java
  src/main/java/softeer/team_pineapple_be/domain/draw/repository/DrawPrizeRepository.java
  src/main/java/softeer/team_pineapple_be/domain/draw/request/DrawPrizeRequest.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawPrizeService.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/domain/QuizReward.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/repository/QuizRewardRepository.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/request/QuizRewardUploadRequest.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizService.java
  src/main/java/softeer/team_pineapple_be/global/auth/annotation/Admin.java
  src/main/java/softeer/team_pineapple_be/global/auth/exception/AuthErrorCode.java
  src/main/java/softeer/team_pineapple_be/global/auth/interceptor/JwtInterceptor.java
  src/main/java/softeer/team_pineapple_be/global/cloud/service/MultipartFileWrapper.java
  src/main/java/softeer/team_pineapple_be/global/cloud/service/S3DeleteService.java
  src/main/java/softeer/team_pineapple_be/global/cloud/service/S3UploadService.java
  src/main/resources/messages.properties
Labels: api 추가, 기능 추가, 예외처리

#94 Feat/#92,#93/일자별 응모 정보 어드민 기능 추가, 퀴즈 어드민 이미지 처리
  src/main/java/softeer/team_pineapple_be/domain/admin/controller/AdminController.java
  src/main/java/softeer/team_pineapple_be/domain/draw/domain/DrawDailyMessageInfo.java
  src/main/java/softeer/team_pineapple_be/domain/draw/exception/DrawErrorCode.java
  src/main/java/softeer/team_pineapple_be/domain/draw/request/DrawDailyMessageModifyRequest.java
  src/main/java/softeer/team_pineapple_be/domain/draw/response/DrawDailyMessageResponse.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawService.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/domain/QuizInfo.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/exception/QuizErrorCode.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/request/QuizInfoModifyRequest.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizService.java
  src/main/resources/messages.properties
Labels: api 추가, 기능 개선, 기능 추가

#96 Feat/#95/경품 확률 및 상품에 관한 어드민 관리 추가
  src/main/java/softeer/team_pineapple_be/domain/admin/controller/AdminController.java
  src/main/java/softeer/team_pineapple_be/domain/draw/domain/DrawRewardInfo.java
  src/main/java/softeer/team_pineapple_be/domain/draw/request/DrawProbabilityRequest.java
  src/main/java/softeer/team_pineapple_be/domain/draw/request/DrawRewardInfoListRequest.java
  src/main/java/softeer/team_pineapple_be/domain/draw/response/DrawProbabilityResponse.java
  src/main/java/softeer/team_pineapple_be/domain/draw/response/DrawRewardInfoListResponse.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawProbabilityService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawRewardInfoService.java
Labels: api 추가, 기능 추가

#100 Feat/#95,#99/어드민 페이지 이벤트 지표 및 경품 추가
  src/main/java/softeer/team_pineapple_be/domain/admin/controller/AdminController.java
  src/main/java/softeer/team_pineapple_be/domain/admin/repisotory/EventDayInfoRepository.java
  src/main/java/softeer/team_pineapple_be/domain/draw/request/DrawRewardInfoListRequest.java
  src/main/java/softeer/team_pineapple_be/domain/draw/response/DrawHistoryPageResponse.java
  src/main/java/softeer/team_pineapple_be/domain/draw/response/DrawHistoryResponse.java
  src/main/java/softeer/team_pineapple_be/domain/draw/response/DrawRemainingResponse.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawHistoryService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawRewardInfoService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawService.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/response/QuizHistoryResponse.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizHistoryService.java
Labels: api 추가, 기능 추가

#102 Feat/#101/ 어드민 지표 분리를 위한 수정
  src/main/java/softeer/team_pineapple_be/domain/quiz/response/QuizHistoryResponse.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizHistoryService.java
Labels: 기능 개선

#103 Feat/#101/지표 가독성 개선을 위한 수정
  src/main/java/softeer/team_pineapple_be/domain/quiz/response/QuizHistoryResponse.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizHistoryService.java
Labels: 기능 개선

#109 feat/#108/이벤트 경품 UI에 필요한 경품 정보 추가
  src/main/java/softeer/team_pineapple_be/domain/draw/controller/DrawController.java
  src/main/java/softeer/team_pineapple_be/domain/draw/exception/DrawErrorCode.java
  src/main/java/softeer/team_pineapple_be/domain/draw/response/DrawRewardImageResponse.java
  src/main/java/softeer/team_pineapple_be/domain/draw/response/DrawRewardInfoResponse.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawPrizeService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawProbabilityService.java
Labels: 기능 개선, 기능 추가

#111 Feat/#110/멀티파트 폼 데이터 에러 처리
  src/main/java/softeer/team_pineapple_be/domain/admin/controller/AdminController.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawProbabilityService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawRewardInfoService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawService.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizService.java
  src/main/java/softeer/team_pineapple_be/global/cloud/service/exception/S3ErrorCode.java
Labels: 기능 개선, 버그 픽스

#113 Feat/#112/단축 url 생성
  src/main/java/softeer/team_pineapple_be/domain/comment/controller/CommentController.java
  src/main/java/softeer/team_pineapple_be/domain/comment/service/CommentService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawProbabilityService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawService.java
  src/main/java/softeer/team_pineapple_be/global/common/utils/RandomUtils.java
  src/main/java/softeer/team_pineapple_be/global/shortenurl/controller/ShortenUrlController.java
  src/main/java/softeer/team_pineapple_be/global/shortenurl/domain/ShortenUrl.java
  src/main/java/softeer/team_pineapple_be/global/shortenurl/exception/ShortenUrlErrorCode.java
  src/main/java/softeer/team_pineapple_be/global/shortenurl/repository/ShortenUrlRepository.java
  src/main/java/softeer/team_pineapple_be/global/shortenurl/request/ShortenUrlRequest.java
  src/main/java/softeer/team_pineapple_be/global/shortenurl/response/ShortenUrlResponse.java
  src/main/java/softeer/team_pineapple_be/global/shortenurl/service/ShortenUrlService.java
Labels: api 추가, 기능 추가

#115 Feat/#114/메시지 전송 기능 구현
  build.gradle
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawPrizeService.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/repository/QuizRewardRepository.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizService.java
  src/main/java/softeer/team_pineapple_be/global/auth/service/PhoneAuthorizationService.java
  src/main/java/softeer/team_pineapple_be/global/cloud/service/S3DownloadService.java
  src/main/java/softeer/team_pineapple_be/global/config/RestClientConfig.java
  src/main/java/softeer/team_pineapple_be/global/message/MessageService.java
  src/main/java/softeer/team_pineapple_be/global/message/exception/MessageErrorCode.java
  src/main/java/softeer/team_pineapple_be/global/shortenurl/controller/ShortenUrlController.java
  src/main/java/softeer/team_pineapple_be/global/shortenurl/service/ShortenUrlService.java
  src/main/resources/application.yml
  src/test/java/softeer/team_pineapple_be/domain/quiz/service/QuizServiceTest.java
Labels: 버그 픽스, 기능 추가

#116 Feat/#112/단축 url 로직 수정, 1등 추첨 로직 추가
  src/main/java/softeer/team_pineapple_be/domain/admin/controller/AdminController.java
  src/main/java/softeer/team_pineapple_be/domain/admin/exception/AdminErrorCode.java
  src/main/java/softeer/team_pineapple_be/domain/admin/response/TopPrizeWinnerResponse.java
  src/main/java/softeer/team_pineapple_be/domain/admin/service/TopPrizeWinnerService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/exception/DrawErrorCode.java
  src/main/java/softeer/team_pineapple_be/global/cloud/service/MultipartFileWrapper.java
  src/main/java/softeer/team_pineapple_be/global/cloud/service/S3DeleteService.java
  src/main/java/softeer/team_pineapple_be/global/common/utils/RandomUtils.java
  src/main/java/softeer/team_pineapple_be/global/config/CorsMvcConfig.java
  src/main/java/softeer/team_pineapple_be/global/shortenurl/controller/ShortenUrlController.java
  src/main/java/softeer/team_pineapple_be/global/shortenurl/exception/ShortenUrlErrorCode.java
  src/main/java/softeer/team_pineapple_be/global/shortenurl/repository/ShortenUrlRepository.java
  src/main/java/softeer/team_pineapple_be/global/shortenurl/response/ShortenOriginalUrlResponse.java
  src/main/java/softeer/team_pineapple_be/global/shortenurl/service/ShortenUrlService.java
Labels: api 추가, 버그 픽스, 기능 추가

#118 Feat/#117/단축 url 주소 수정
  src/main/java/softeer/team_pineapple_be/global/shortenurl/service/ShortenUrlService.java
Labels: 기능 개선

#121 Feat/#120/Redisson을 이용하여 분산락 구현
  build.gradle
  src/main/java/softeer/team_pineapple_be/TeamPineappleBeApplication.java
  src/main/java/softeer/team_pineapple_be/global/config/RedissonConfig.java
  src/main/java/softeer/team_pineapple_be/global/lock/annotation/DistributedLock.java
  src/main/java/softeer/team_pineapple_be/global/lock/aop/AopForTransaction.java
  src/main/java/softeer/team_pineapple_be/global/lock/aop/DistributedLockAop.java
  src/main/java/softeer/team_pineapple_be/global/lock/util/CustomSpringELParser.java
Labels: 기능 개선, 기능 추가

#122 Fix/#119/경품 당첨 확률 바뀔 때마다 확률 배열에 적용하기
  src/main/java/softeer/team_pineapple_be/domain/admin/controller/AdminController.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/RandomDrawPrizeService.java
Labels: 기능 개선, 버그 픽스

#124 Test/#123/성능 테스트를 위한 분산락 적용
  src/main/java/softeer/team_pineapple_be/domain/comment/service/CommentService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawRewardInfoService.java
Labels: 기능 개선, 기능 추가

#126 [feat] message 설정 해제
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawPrizeService.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizService.java
  src/main/java/softeer/team_pineapple_be/global/auth/service/PhoneAuthorizationService.java
Labels: 기능 개선

#130 Feat/#128/Querydsl 사용을 통한 추가 및 테스트 코드 추가
  build.gradle
  src/main/java/softeer/team_pineapple_be/domain/comment/dao/CommentDao.java
  src/main/java/softeer/team_pineapple_be/domain/comment/response/CommentPageResponse.java
  src/main/java/softeer/team_pineapple_be/domain/comment/service/CommentService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawHistoryService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawPrizeService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawRewardInfoService.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizService.java
  src/main/java/softeer/team_pineapple_be/global/auth/service/PhoneAuthorizationService.java
  src/test/java/softeer/team_pineapple_be/domain/comment/service/CommentServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/draw/service/DrawHistoryServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/draw/service/DrawPrizeServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/draw/service/DrawProbabilityServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/draw/service/DrawRewardInfoServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/draw/service/DrawServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/quiz/service/QuizServiceTest.java
Labels: 설정 추가, 기능 개선, 기능 추가

#132 Feat/#131/동시성 이슈 발생할 수 있는 곳에 분산락 처리
  build.gradle
  src/main/java/softeer/team_pineapple_be/domain/comment/controller/CommentController.java
  src/main/java/softeer/team_pineapple_be/domain/comment/service/CommentLockService.java
  src/main/java/softeer/team_pineapple_be/domain/comment/service/CommentService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/controller/DrawController.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawLockService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawProbabilityService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawService.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/controller/QuizController.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizRedisService.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizService.java
  src/main/java/softeer/team_pineapple_be/global/auth/utils/JwtUtils.java
  src/main/java/softeer/team_pineapple_be/global/config/S3Config.java
  src/main/java/softeer/team_pineapple_be/global/lock/annotation/DistributedLock.java
  src/main/resources/application.yml
  src/test/java/softeer/team_pineapple_be/domain/comment/service/CommentServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/draw/contorller/DrawControllerTest.java
  src/test/java/softeer/team_pineapple_be/domain/draw/service/DrawServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/quiz/controller/QuizControllerTest.java
  src/test/java/softeer/team_pineapple_be/domain/quiz/service/QuizServiceTest.java
Labels: 기능 개선, 기능 추가

#136 Test/#135/테스트 코드 최종 수정
  build.gradle
  src/test/java/softeer/team_pineapple_be/domain/admin/service/EventDayInfoServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/admin/service/TopPrizeWinnerServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/comment/service/CommentLockServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/comment/service/CommentServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/draw/contorller/DrawControllerTest.java
  src/test/java/softeer/team_pineapple_be/domain/draw/service/DrawHistoryServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/draw/service/DrawLockServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/draw/service/DrawProbabilityServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/draw/service/DrawRewardInfoServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/draw/service/DrawServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/member/service/MemberServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/quiz/controller/QuizControllerTest.java
  src/test/java/softeer/team_pineapple_be/domain/quiz/service/QuizHistoryServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/quiz/service/QuizRedisServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/quiz/service/QuizServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/worldcup/service/WorldCupRedisServiceTest.java
  src/test/java/softeer/team_pineapple_be/global/shortenurl/service/ShortenUrlServiceTest.java
Labels: 기능 개선

#138 Feat/#137/글로벌 캐시와 로컬 캐시 적용
  build.gradle
  src/main/java/softeer/team_pineapple_be/TeamPineappleBeApplication.java
  src/main/java/softeer/team_pineapple_be/domain/comment/service/CommentService.java
  src/main/java/softeer/team_pineapple_be/domain/comment/service/LikeRedisService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawProbabilityService.java
  src/main/java/softeer/team_pineapple_be/domain/fcfs/service/FcfsService.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/batch/QuizDailyBatch.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizService.java
  src/main/java/softeer/team_pineapple_be/global/common/domain/enums/CacheType.java
  src/main/java/softeer/team_pineapple_be/global/config/CacheConfig.java
  src/main/java/softeer/team_pineapple_be/global/config/RedisConfig.java
  src/main/resources/application.yml
  src/test/java/softeer/team_pineapple_be/domain/comment/service/CommentLockServiceTest.java
  src/test/java/softeer/team_pineapple_be/domain/comment/service/CommentServiceTest.java
Labels: 설정 추가, 기능 개선, 기능 추가
