Repository softeerbootcamp4th/Team8-PineApple-BE, pull requests merged in 2024-07, with the labels that each got.

#4 Feat/#1/프로젝트 초기 설정
  .DS_Store
  .gitignore
  admin-server/.DS_Store
  build.gradle
  src/main/java/softeer/team_pineapple_be/global/common/domain/BaseTimeEntity.java
  src/main/java/softeer/team_pineapple_be/global/common/domain/enums/Codable.java
  src/main/java/softeer/team_pineapple_be/global/common/domain/enums/Valid.java
  src/main/java/softeer/team_pineapple_be/global/common/domain/enums/converter/AbstractEnumCodeConverter.java
  src/main/java/softeer/team_pineapple_be/global/common/response/DataResponse.java
  src/main/java/softeer/team_pineapple_be/global/common/response/ErrorResponse.java
  src/main/java/softeer/team_pineapple_be/global/common/response/ListResponse.java
  src/main/java/softeer/team_pineapple_be/global/common/response/SuccessResponse.java
  src/main/java/softeer/team_pineapple_be/global/config/SwaggerConfig.java
  src/main/java/softeer/team_pineapple_be/global/exception/handler/RestApiExceptionHandler.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 설정 추가

#5 Feat/#1/프로젝트 초기 설정
  .DS_Store
  .gitignore
  admin-server/.DS_Store
  build.gradle
  src/main/java/softeer/team_pineapple_be/global/common/domain/BaseTimeEntity.java
  src/main/java/softeer/team_pineapple_be/global/common/domain/enums/Codable.java
  src/main/java/softeer/team_pineapple_be/global/common/domain/enums/Valid.java
  src/main/java/softeer/team_pineapple_be/global/common/domain/enums/converter/AbstractEnumCodeConverter.java
  src/main/java/softeer/team_pineapple_be/global/common/response/DataResponse.java
  src/main/java/softeer/team_pineapple_be/global/common/response/ErrorResponse.java
  src/main/java/softeer/team_pineapple_be/global/common/response/ListResponse.java
  src/main/java/softeer/team_pineapple_be/global/common/response/SuccessResponse.java
  src/main/java/softeer/team_pineapple_be/global/config/SwaggerConfig.java
  src/main/java/softeer/team_pineapple_be/global/exception/handler/RestApiExceptionHandler.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 설정 추가, 기능 추가

#9 Feat/#7/유저 기능 및 문자 인증 로그인 기능 구현
  src/main/java/softeer/team_pineapple_be/domain/member/controller/LoginController.java
  src/main/java/softeer/team_pineapple_be/domain/member/domain/Member.java
  src/main/java/softeer/team_pineapple_be/domain/member/domain/MemberAuthorization.java
  src/main/java/softeer/team_pineapple_be/domain/member/repository/MemberAuthorizationRepository.java
  src/main/java/softeer/team_pineapple_be/domain/member/repository/MemberRepository.java
  src/main/java/softeer/team_pineapple_be/domain/member/request/LoginAuthCodeRequest.java
  src/main/java/softeer/team_pineapple_be/domain/member/request/LoginPhoneNumberRequest.java
  src/main/java/softeer/team_pineapple_be/domain/member/response/MemberInfoResponse.java
  src/main/java/softeer/team_pineapple_be/domain/member/service/MemberAuthorizationService.java
  src/main/java/softeer/team_pineapple_be/global/auth/service/PhoneAuthorizationService.java
  src/main/java/softeer/team_pineapple_be/global/common/utils/RandomUtils.java
  src/main/resources/application.yml
Labels: 설정 추가, api 추가, 기능 추가

#14 Feat/#13/Quiz 참여여부(툴박스얻기버튼) api 구현
  src/main/java/softeer/team_pineapple_be/domain/member/domain/Member.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/controller/QuizController.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/domain/QuizHistory.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/domain/QuizInfo.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/repository/QuizHistoryRepository.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/response/QuizInfoResponse.java
  src/main/java/softeer/team_pineapple_be/domain/quiz/service/QuizService.java
Labels: api 추가, 기능 개선, 기능 추가

#19 Feat/#17/기대평 API 구현
  src/main/java/softeer/team_pineapple_be/domain/comment/controller/CommentController.java
  src/main/java/softeer/team_pineapple_be/domain/comment/domain/Comment.java
  src/main/java/softeer/team_pineapple_be/domain/comment/domain/CommentLike.java
  src/main/java/softeer/team_pineapple_be/domain/comment/domain/id/LikeId.java
  src/main/java/softeer/team_pineapple_be/domain/comment/repository/CommentLikeRepository.java
  src/main/java/softeer/team_pineapple_be/domain/comment/repository/CommentRepository.java
  src/main/java/softeer/team_pineapple_be/domain/comment/request/CommentLikeRequest.java
  src/main/java/softeer/team_pineapple_be/domain/comment/request/CommentRequest.java
  src/main/java/softeer/team_pineapple_be/domain/comment/response/CommentPageResponse.java
  src/main/java/softeer/team_pineapple_be/domain/comment/response/CommentResponse.java
  src/main/java/softeer/team_pineapple_be/domain/comment/service/CommentService.java
Labels: api 추가, 기능 추가

#21 Feat/#20/경품 추첨 기능 구현
  src/main/java/softeer/team_pineapple_be/TeamPineappleBeApplication.java
  src/main/java/softeer/team_pineapple_be/domain/draw/controller/DrawController.java
  src/main/java/softeer/team_pineapple_be/domain/draw/domain/DrawDailyMessageInfo.java
  src/main/java/softeer/team_pineapple_be/domain/draw/domain/DrawHistory.java
  src/main/java/softeer/team_pineapple_be/domain/draw/domain/DrawPrize.java
  src/main/java/softeer/team_pineapple_be/domain/draw/domain/DrawProbability.java
  src/main/java/softeer/team_pineapple_be/domain/draw/domain/DrawRewardInfo.java
  src/main/java/softeer/team_pineapple_be/domain/draw/repository/DrawDailyMessageInfoRepository.java
  src/main/java/softeer/team_pineapple_be/domain/draw/repository/DrawHistoryRepository.java
  src/main/java/softeer/team_pineapple_be/domain/draw/repository/DrawPrizeRepository.java
  src/main/java/softeer/team_pineapple_be/domain/draw/repository/DrawProbabilityRepository.java
  src/main/java/softeer/team_pineapple_be/domain/draw/repository/DrawRewardInfoRepository.java
  src/main/java/softeer/team_pineapple_be/domain/draw/request/SendPrizeRequest.java
  src/main/java/softeer/team_pineapple_be/domain/draw/response/DrawLoseResponse.java
  src/main/java/softeer/team_pineapple_be/domain/draw/response/DrawResponse.java
  src/main/java/softeer/team_pineapple_be/domain/draw/response/DrawWinningResponse.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawPrizeService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/DrawService.java
  src/main/java/softeer/team_pineapple_be/domain/draw/service/RandomDrawPrizeService.java
  src/main/java/softeer/team_pineapple_be/domain/member/domain/Member.java
  src/main/java/softeer/team_pineapple_be/domain/member/repository/MemberRepository.java
  src/main/java/softeer/team_pineapple_be/global/common/utils/RandomUtils.java
  src/main/java/softeer/team_pineapple_be/global/message/MessageService.java
Labels: 설정 추가, api 추가, 기능 추가
